name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.51.0
    steps:
    - uses: actions/checkout@v1
    - name: Install ARM toolchain
      run: rustup target add thumbv7em-none-eabihf
    - name: Build lib
      run: cargo build --verbose
    - name: Build examples
      run: cargo build --examples --verbose
    #- name: Run tests
    #  run: cargo test --verbose
